import { Shield, Zap, Users } from "lucide-react";

const steps = [
  {
    icon: Shield,
    title: "Reliable Tours",
    description:
      "We insist on a very high tour quality and therefore only work with qualified and professional tour companies.",
  },
  {
    icon: Zap,
    title: "Fast Booking",
    description:
      "Zourney is automatically offsetting the carbon footprint generated by all tour bookings, for online package tour booking platforms.",
  },
  {
    icon: Users,
    title: "Pesonalized Trips",
    description:
      "Our local travel experts will design a trip that matches your unique interests and special requirements, booking everything.",
  },
];

export default function BookingProcess() {
  return (
    <section className="py-20">
      <div className="mx-auto max-w-7xl px-4">
        <p className="mb-2 text-center text-sm font-semibold tracking-widest text-primary">
          Convenient and Easy Tour
        </p>
        <h2 className="mb-12 text-center text-3xl text-accent md:text-4xl">
          Booking Process
        </h2>
        <div className="grid grid-cols-1 gap-10 md:grid-cols-3">
          {steps.map((s) => (
            <div key={s.title} className="text-center">
              <div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-full bg-primary/10">
                <s.icon className="h-7 w-7 text-primary" />
              </div>
              <h3 className="mb-3 text-xl font-semibold text-accent">{s.title}</h3>
              <p className="text-sm leading-relaxed text-body-text">{s.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
