const reasons = [
  {
    number: "01",
    title: "Best Prices",
    description:
      "Amazing travel experiences are priceless. With a Best Price Guarantee on all tours, you always get the best deal.",
  },
  {
    number: "02",
    title: "Wide Selection of Tours",
    description:
      "Offering 29+ different Cappadocia tours, allows you to easily find and book your favourite day tours and package tours.",
  },
  {
    number: "03",
    title: "Qualified Tour Operators",
    description:
      "We insist on a very high tour quality and therefore only work with qualified and professional tour companies.",
  },
  {
    number: "04",
    title: "Professional Tour Guide",
    description:
      "For all tours, you can make an enquiry directly with the tour operator, and get a customised tour offer.",
  },
  {
    number: "05",
    title: "Fast Booking",
    description:
      "Vacation Cappadocia is automatically offsetting the carbon footprint generated by all tour bookings, for online package tour booking platforms.",
  },
  {
    number: "06",
    title: "Pesonalized Trips",
    description:
      "Our local travel experts will design a trip that matches your unique interests and special requirements, booking everything.",
  },
];

export default function WhyBookWithUs() {
  return (
    <section className="py-20 px-4 bg-light-bg">
      <div className="max-w-7xl mx-auto">
        <span className="block text-primary text-sm font-semibold uppercase tracking-widest text-center mb-2">
          why book with us
        </span>
        <h2 className="text-3xl md:text-4xl text-center text-accent mb-14">
          Convenient and Easy Tour Booking Process
        </h2>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8">
          {reasons.map((r) => (
            <div
              key={r.number}
              className="bg-white rounded-[3px] p-8 shadow-sm hover:shadow-lg transition-shadow"
            >
              <span className="text-5xl font-bold text-primary/20">
                {r.number}
              </span>
              <h3 className="text-xl font-semibold text-accent mt-3 mb-3">
                {r.title}
              </h3>
              <p className="text-gray-600 leading-relaxed">{r.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
